const express = require("express")
const Router = express.Router()
const authController = require("../controllers/auth")
const userController = require("../controllers/user")
const uploadMiddleware = require("../middlewares/uploadImages")
Router.post("/login", authController.login)
Router.post("/logout", authController.logout)
Router.post("/refresh", authController.refresh)
// Router.post("/register", uploadMiddleware.uploadUser, authController.register)
module.exports = Router
